# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1473, 766)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 130, 1431, 581))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.antideriv_gr = PlotWidget(self.layoutWidget)
        self.antideriv_gr.setObjectName("antideriv_gr")
        self.horizontalLayout_6.addWidget(self.antideriv_gr)
        self.graphic = PlotWidget(self.layoutWidget)
        self.graphic.setObjectName("graphic")
        self.horizontalLayout_6.addWidget(self.graphic)
        self.deriv_gr = PlotWidget(self.layoutWidget)
        self.deriv_gr.setObjectName("deriv_gr")
        self.horizontalLayout_6.addWidget(self.deriv_gr)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(21, 32, 1431, 81))
        self.widget.setObjectName("widget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.antiderivative_output = QtWidgets.QPlainTextEdit(self.widget)
        self.antiderivative_output.setEnabled(False)
        self.antiderivative_output.setObjectName("antiderivative_output")
        self.horizontalLayout_4.addWidget(self.antiderivative_output)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.start = QtWidgets.QLineEdit(self.widget)
        self.start.setObjectName("start")
        self.horizontalLayout.addWidget(self.start)
        self.l3 = QtWidgets.QLabel(self.widget)
        self.l3.setObjectName("l3")
        self.horizontalLayout.addWidget(self.l3)
        self.to = QtWidgets.QLineEdit(self.widget)
        self.to.setObjectName("to")
        self.horizontalLayout.addWidget(self.to)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.l1 = QtWidgets.QLabel(self.widget)
        self.l1.setObjectName("l1")
        self.horizontalLayout_2.addWidget(self.l1)
        self.func = QtWidgets.QLineEdit(self.widget)
        self.func.setObjectName("func")
        self.horizontalLayout_2.addWidget(self.func)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.params = QtWidgets.QLineEdit(self.widget)
        self.params.setObjectName("params")
        self.horizontalLayout_7.addWidget(self.params)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.derivative_output = QtWidgets.QPlainTextEdit(self.widget)
        self.derivative_output.setEnabled(False)
        self.derivative_output.setObjectName("derivative_output")
        self.horizontalLayout_5.addWidget(self.derivative_output)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Построить"))
        self.antiderivative_output.setPlainText(_translate("MainWindow", "Первообразная"))
        self.label.setText(_translate("MainWindow", "x ∈["))
        self.l3.setText(_translate("MainWindow", ";"))
        self.label_2.setText(_translate("MainWindow", "]"))
        self.l1.setText(_translate("MainWindow", "f(x) = "))
        self.label_3.setText(_translate("MainWindow", "Параметры:"))
        self.derivative_output.setPlainText(_translate("MainWindow", "Производная"))

from pyqtgraph import PlotWidget
